name: Question
description: Ask a ultralytics_ros question
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for asking a ultralytics_ros Question!

  - type: dropdown
    attributes:
      label: Branch
      description: |
        Please select the branch you are using.
      multiple: true
      options:
        - "melodic-devel"
        - "noetic-devel"
        - "humble-devel"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Question
      description: A description of your question.
      placeholder: |
        💡 ProTip! Include as much information as possible (screenshots, logs, tracebacks etc.) to receive the most helpful response.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional
      description: Anything else you would like to share?
