name: formatter

on:
  pull_request:

jobs:
  formatter:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8.10]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format libxml2-utils
          python -m pip install --upgrade pip
          pip install autoflake autopep8 isort
      - name: clang-format
        run: find . -type f \( -name "*.cpp" -or -name "*.hpp" -or -name "*.h" \) -exec clang-format -i -style=file {} \;
      - name: xmllint
        run: find . -type f \( -name "*.xml" -or -name "*.launch" -or -name "*.xacro" \) -exec xmllint --format -o {} {} \;
      - name: autoflake
        run: find . -type f -name "*.py" -exec autoflake {} \;
      - name: autopep8
        run: find . -type f -name "*.py" -exec autopep8 -i {} \;
      - name: isort
        run: find . -type f -name "*.py" -exec isort {} \;
      - name: auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: apply format
